spring.application.name=franchise-api

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

spring.cache.type=redis

spring.threads.virtual.enabled=true

server.port=${SERVER_PORT}
server.shutdown=graceful

management.endpoints.web.exposure.include=health,info,metrics,caches
management.endpoint.health.show-components=always
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=false
management.health.defaults.enabled=false
management.health.db.enabled=true
management.health.ping.enabled=true
management.health.redis.enabled=true

top-products.cache.ttl-seconds=60

spring.mvc.problemdetails.enabled=false

springdoc.swagger-ui.path=/swagger-ui.html
